---
################################################################################
# Any local customizations should be placed inside the .kitchen.local.yml, which
# will not be checked in or overwritten. You may also use ~/.kitchen/config.yml
# or environment variables like VAGRANT_DEFAULT_PROVIDER. Anything in those will
# take precedence over anything set in `.kitchen.yml`.
################################################################################
driver:
  name: vagrant # provide a default test-kitchen driver, vagrant

provisioner:
  name: chef_zero
  nodes_path: 'test/fixtures/nodes'
  data_bags_path: 'test/fixtures/data_bags'
  environments_path: 'test/fixtures/environments'
  client_rb:
    environment: _default
  attributes:
    java:
      jdk_version: '8'

platforms:
  - name: ubuntu-16.04
    run_list:
    - recipe[apt]
    - recipe[curl]
    - recipe[java]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
    - recipe[curl]
    - recipe[java]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
    - recipe[curl]
    - recipe[java]
  - name: centos-7.2
    run_list:
    - recipe[yum]
    - recipe[curl]
    - recipe[java]
  - name: centos-6.7
    run_list:
    - recipe[yum]
    - recipe[curl]
    - recipe[java]

suites:
  - name: default
    require_chef_omnibus: 12.15.19
    run_list:
      - recipe[embulk_test::default_with_plugins]
    attributes:
      embulk:
        user: 'vagrant'
        group: 'vagrant'
        home: '/home/vagrant'
