driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken
  nodes_path: 'test/fixtures/nodes'
  data_bags_path: 'test/fixtures/data_bags'
  environments_path: 'test/fixtures/environments'
  client_rb:
    environment: _default
  attributes:
    java:
      jdk_version: '8'

platforms:
- name: centos-6
  run_list:
  - recipe[apt]
  - recipe[curl]
  - recipe[java]
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install openssl which initscripts net-tools wget

- name: centos-7
  run_list:
  - recipe[apt]
  - recipe[curl]
  - recipe[java]
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools

- name: fedora-latest
  run_list:
  - recipe[apt]
  - recipe[curl]
  - recipe[java]
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum which systemd-sysv initscripts wget net-tools

- name: ubuntu-14.04
  run_list:
  - recipe[apt]
  - recipe[curl]
  - recipe[java]
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

- name: ubuntu-16.04
  run_list:
  - recipe[apt]
  - recipe[curl]
  - recipe[java]
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

suites:
  - name: default
    require_chef_omnibus: 12.15.19
    run_list:
      - recipe[embulk_test::default_with_plugins]
    attributes:
      embulk:
        user: 'root'
        group: 'root'
        home: '/root'
